### ISSUE TITLE
Travis tests broken

### ISSUE THREAD

**Issue by borisovg** [whitequark/ipaddr.js#121]
Noticed this while testing conversion to plain JS (as per #118).

See test output at https://travis-ci.org/whitequark/ipaddr.js/jobs/553822408. Test returns an error but Travis thinks this is fine because CoffeeScript compiler still returns code "0".

String.prototype.padStart() is not available until Node v8 apparently.

**Comment by borisovg** [comment]
```✖ converts IPv6 to string correctly
TypeError: Object 2001 has no method 'padStart'
    at IPv6.<anonymous> (/home/travis/build/whitequark/ipaddr.js/lib/ipaddr.js:265:31)
    at IPv6.ipaddr.IPv6.IPv6.toFixedLengthString (/home/travis/build/whitequark/ipaddr.js/lib/ipaddr.js:292:10)
    at Object.module.exports.converts IPv6 to string correctly (/home/travis/build/whitequark/ipaddr.js/test/ipaddr.test.coffee:155:21)
    at Object.<anonymous> (/home/travis/build/whitequark/ipaddr.js/node_modules/nodeunit/lib/core.js:231:5)
    at /home/travis/build/whitequark/ipaddr.js/node_modules/nodeunit/lib/core.js:231:5
    at Object.exports.runTest (/home/travis/build/whitequark/ipaddr.js/node_modules/nodeunit/lib/core.js:51:16)
    at /home/travis/build/whitequark/ipaddr.js/node_modules/nodeunit/lib/core.js:135:5
    at /home/travis/build/whitequark/ipaddr.js/node_modules/nodeunit/deps/async.js:467:8
    at iterate (/home/travis/build/whitequark/ipaddr.js/node_modules/nodeunit/deps/async.js:139:7)
    at /home/travis/build/whitequark/ipaddr.js/node_modules/nodeunit/deps/async.js:151:19
    at /home/travis/build/whitequark/ipaddr.js/node_modules/nodeunit/deps/async.js:468:12
    at Object._onImmediate (/home/travis/build/whitequark/ipaddr.js/node_modules/nodeunit/lib/types.js:149:5)
    at processImmediate [as _immediateCallback] (timers.js:341:12)```

**Comment by whitequark** [comment]
I don't really have time to fix this myself soon.

**Comment by borisovg** [comment]
At least in the context of the "decaffeination" PR I can copy paste the polyfill as a quick fix, if that is OK with you?

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/padStart

**Comment by whitequark** [comment]
Sure, copy-paste for small snippets like that is always OK.

**Comment by borisovg** [comment]
In the end I just replaced with a tiny custom function because the MDN polyfill referred to String.repeat() which is not available before Node v4 either.
